{
  "hash": "f44f1c41ef9a1bef87dca718ab6c7583",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Paired and Two Sample t-tests\"\naffiliation: \"CSU, Chico MATH 315\"\nauthor: \"Edward A. Roualdes\"\nformat:\n  revealjs:\n    incremental: true\n    scrollable: true\n    self-contained: true\ntbl-cap-location: bottom\nexecute:\n  echo: true\n---\n\n\n\n# Recap\n\n## Recap: $t$-distribution\n\nSo far, we have used the t-distribution for confidence intervals or hypothesis\ntests of *one mean* (proportions are means).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(df$x, mu = some_value, conf.level = 0.95)\n```\n:::\n\n\n# Paired Data\n\n## Paired Data, definition\n\n**Paired data** are somehow intimately connected.\n\nTwo sets of observations are paired if each observation in one set has a special\ncorrespondence or connection with exactly one observation in the other data set.\n\n\n## Paired Data, by example\n\nTell me whether or not these data are paired.\n\n* two website's price for the same book\n* eye sight ratings by person\n* jumping spider vertical (jump height)\n* upper verse lower bird beak lengths\n* weights of male and female babies\n\n\n## Paired Data, t-test\n\nIf the data are paired, their difference has direct and interpretable meaning\nboth in English and in statistics; $X_{i,diff} = X_{i,a} - X_{i,b}$ has meaning.\nTherefore\n\n$$\\bar{X}_{diff} \\quad \\text{ and } \\quad s_{\\bar{X}_{diff}}$$\n\nare simply fancy ways to write new random variables.\n\n# An Example\n\n## Paired Data, confidence interval\n\nAre textbooks actually cheaper online?  Compare the price of textbooks at the\nUniversity of California, Los Angeles' (UCLA's) bookstore and prices at\nAmazon.com.  Seventy-three UCLA courses were randomly sampled in Spring 2010.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbooks <- read.csv(\"https://raw.githubusercontent.com/roualdes/data/master/books.csv\")\n## look at data in RStudio\n## what plot should we make?\n```\n:::\n\n\n# Paired Data, confidence interval\n\nPlot the data!\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsuppressMessages(library(ggplot2))\nggplot(books, aes(uclaNew, amazNew),\n       xlab=\"UCLA price ($)\", ylab=\"Amazon price ($)\") +\n    geom_point() +\n    geom_abline(intercept=0, slope=1)\n```\n:::\n\n\n## Paired Data, confidence interval\n\nCalculate and interpret a 95% confidence interval of the difference in Amazon.com versus UCLA's book prices.\n\n## Paired Data, confidence interval\n\n::: {.cell}\n\n```{.r .cell-code}\nd <- books$amazNew - books$uclaNew # create new variable\n# now the same as before\nt.test(d, conf.level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  d\nt = -7.6488, df = 72, p-value = 6.928e-11\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n -16.087652  -9.435636\nsample estimates:\nmean of x \n-12.76164 \n```\n\n\n:::\n:::\n\n\n## Paired Data, confidence interval\n\n\n::: {.cell}\n\n:::\n\n\nWe are $95$\\% confident that the true mean difference in price between Amazon.com and\nUCLA's books is between -16.09 and\n-9.44.\n\n## Paired Data, hypothesis test\n\nSet up, evaluate, and conclude in context a hypothesis test at $\\alpha = 0.05$.\n\n\n## Paired Data, hypothesis test\nThe natural hypotheses are\n\n$$ H_0: \\mu_{diff} = 0 \\text{ versus } H_1: \\mu_{diff} \\ne 0. $$\n\n## Paired Data, hypothesis test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd <- books$amazNew - books$uclaNew # create new variable\nt.test(d, mu = 0, conf.level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  d\nt = -7.6488, df = 72, p-value = 6.928e-11\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n -16.087652  -9.435636\nsample estimates:\nmean of x \n-12.76164 \n```\n\n\n:::\n:::\n\n\n\n## Paired Data, hypothesis test\n\nBecuase p-value$<0.0001 < \\alpha = 0.05$, we reject $H_0$.  There is\ninsufficient evidence to claim that Amazon.com and UCLA's book prices are the\nsame.\n\n# Two Sample t-test\n\n\n## Two Sample t-test\n\nTwo sample t-tests estimate the difference between two population means from two\nindependent samples of data.  We estimate $\\mu_a - \\mu_b$ with the point\nestimator $\\bar{X}_a - \\bar{X}_b$.\n\n\n## Two Sample t-test, confidence interval\n\nConfidence intervals for two sample t-tests follow the same pattern as before,\n\n$$ (\\bar{X}_a - \\bar{X}_b) \\pm t^*_{df} \\cdot s_{\\bar{X}_a - \\bar{X}_b}. $$\n\n## Two Sample t-test, hypothesis tests\n\nTest statistics for two sample t-tests follow the same pattern as before, and\np-values are exactly the same.\n\n\n\n# Two Sample t-test, example\n\n\n# Two Sample t-test, example\n\nConsider the data set `ape::carnivora`.  Calculate a $98$\\% confidence\ninterval for the difference in mean longevity between the two SuperFamilies\nCaniformia and Feliformia.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsuppressMessages(library(ape))\ndata(carnivora)\n# ?carnivora\n# look at importing data\n```\n:::\n\n\n\n## Two Sample t-test, confidence interval\n\nA $98$\\% CI, difference in longevity by Caniformia and Feliformia.\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(LY~SuperFamily, data=carnivora,\n       conf.level=0.98)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  LY by SuperFamily\nt = 1.0243, df = 37.394, p-value = 0.3123\nalternative hypothesis: true difference in means between group Caniformia and group Feliformia is not equal to 0\n98 percent confidence interval:\n -28.13845  69.13511\nsample estimates:\nmean in group Caniformia mean in group Feliformia \n                192.4583                 171.9600 \n```\n\n\n:::\n:::\n\n\n\n## Two Sample t-test, confidence interval\n\nWe are $98$\\% confidence that the population difference in mean longevity\nbetween the SuperFamlies Caniformia and Feliformia is between\n-28.1 and 69.1.\n\n\n## Two Sample t-test, hypothesis test\n\nSet up, evaluate, and conclude in context a hypothesis test at $\\alpha = 0.02$.\n\n\n\n## Two Sample t-test, hypothesis test\n\nThe natural hypotheses are\n\n$$ H_0: \\mu_C = \\mu_F \\text{ versus } H_1: \\mu_C \\ne \\mu_F $$\n\nand $\\alpha = 0.02$.\n\n\n## Two Sample t-test, hypothesis test\n\nBecause p-value $=0.31 > \\alpha = 0.02$, we fail to\nreject $H_0$.  There is insufficient evidence to claim that the true difference\nin mean longevity between Caniformia and Feliformia is different.\n\n\n# Take Away\n\n## Take Away\n\nOverall things have stayed pretty much the same: confidence intervals,\nhypothesis tests, and interpretations.  Now we have new types of data we can\nwork with.\n\n\n* Paired data\n    * Two variables are intimately connected $\\Rightarrow$ their difference has meaning\n    * create one variable from the two $\\Rightarrow$ one sample t-test\n\n* Two sample data\n    * Two variables are independent\n    * Point estimate is difference of means\n    * Standard error follows from independence\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}