{
  "hash": "077c68facd61ffc6155106439598937f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntoc: false\nformat: html\n---\n\n# MATH 315 Practice Exam 02, solutions\n\n\n::: {.cell}\n\n:::\n\n\n1. Describe the Central Limit Theorem and also include why it's appropriate to use a symmetric confidence interval.\n\n2. Consider the variable `LS` (litter size) from the carnivora dataset.  The output of a t-test is below.  Answer the following question based on this output.\n\n\n   ::: {.cell}\n   \n   ```{.r .cell-code}\n   carnivora <- read.csv(\"https://raw.githubusercontent.com/roualdes/data/refs/heads/master/carnivora.csv\")\n   t.test(carnivora$LS, mu = 2, conf.level = 0.9)\n   ```\n   \n   ::: {.cell-output .cell-output-stdout}\n   \n   ```\n   \n   \tOne Sample t-test\n   \n   data:  carnivora$LS\n   t = 9.87, df = 109, p-value < 2.2e-16\n   alternative hypothesis: true mean is not equal to 2\n   90 percent confidence interval:\n    3.024773 3.438863\n   sample estimates:\n   mean of x \n    3.231818 \n   ```\n   \n   \n   :::\n   :::\n\n\n   a. How many observations were measured / what is the sample size?\n   \n   df + 1 = 110\n\n   b. Interpret, in context of these data, the confidence interval.\n   \n   We are 95% confident that the true mean litter size of animals from the Order Carnivora is between 3.02 and 3.44.\n\n   c. Did this confidence interval capture the true population\n   parameter it is targeting?\n   \n   We don't know.  We know that the procedure used to create this confidence interval would capture the true mean 90% of the time, if we were to collect new data and make a new confidence interval from each new dataset.  But this particular confidence interval, we can't say.\n\n   d. If we had instead more observations in the sample, would the confidence interval\n   be narrower or wider? Explain why, using concepts and keywords from\n   this class.\n   \n   More observations leads to increased accuracy, since the standard error decreases, and so the confidence interval will narrow.\n\n   e. If we instead made a 98% confidence interval, would the\n   confidence interval be narrower or wider? Explain why, using concepts\n   and keywords from this class.\n   \n   With a greater confidence level, a confidence interval will widen because a higher confidence level will capture more of the most likely values that the true population mean could take on.\n\n3. Consider again the carnivora dataset, where GL represents gestation length in days and WA represents weaning age in days.  The output of a t-test is below.\n   Answer the following questions based on this output.\n\n\n   ::: {.cell}\n   \n   ```{.r .cell-code}\n   carnivora$diff <- carnivora$GL - carnivora$WA\n   t.test(carnivora$diff, conf.level = 0.99)\n   ```\n   \n   ::: {.cell-output .cell-output-stdout}\n   \n   ```\n   \n   \tOne Sample t-test\n   \n   data:  carnivora$diff\n   t = -2.5586, df = 57, p-value = 0.01319\n   alternative hypothesis: true mean is not equal to 0\n   99 percent confidence interval:\n    -69.848307   1.420721\n   sample estimates:\n   mean of x \n   -34.21379 \n   ```\n   \n   \n   :::\n   :::\n\n\n   a. What type of hypothesis test is this, what is the proper name?\n   \n   paired t-test\n\n   b. Write the corresponding null and alternative hypotheses using proper statistical symbols.\n   \n   H0: μ_diff = 0\n   H1: μ_diff != 0\n\n   c. What is the value for the level of significance?\n   \n   .01\n\n   d. Write a statistical conclusion using the p-value.\n   \n   Because the p-value is greater than the level of significance we fail to reject H0\n\n   e. Write an interpretation of the conclusion from d. with minimal\n   statistical jargon.\n   \n   There is evidence that the true mean difference between gestation length and weaning age in days is not different from 0.\n\n   f. Explain why the confidence interval supports the same conclusion\n   as the p-value.\n   \n   Becuase the confidence interval captures the value in H0, namely 0, the confidence interval agrees with the hypothesis test.\n\n4. Consider again the carnivora dataset.  The output of a t-test is below.\n   Answer the following questions based on this output.\n\n\n   ::: {.cell}\n   \n   ```{.r .cell-code}\n   t.test(LS ~ SuperFamily, data = carnivora, conf.level = 0.9)\n   ```\n   \n   ::: {.cell-output .cell-output-stdout}\n   \n   ```\n   \n   \tWelch Two Sample t-test\n   \n   data:  LS by SuperFamily\n   t = 4.4126, df = 76.408, p-value = 3.306e-05\n   alternative hypothesis: true difference in means between group Caniformia and group Feliformia is not equal to 0\n   90 percent confidence interval:\n    0.620908 1.373465\n   sample estimates:\n   mean in group Caniformia mean in group Feliformia \n                   3.712281                 2.715094 \n   ```\n   \n   \n   :::\n   :::\n\n\n   a. What type of hypothesis test is this, what is the proper name?\n   \n   two sample t-test\n\n   b. Write the corresponding null and alternative hypotheses using\n   proper statistical symbols.\n   \n   H0: µ_c = µ_f\n   H1: µ_c != µ_f\n\n   c. What does this output tell you about these data? Write a\n   conclusion with little to no statistical jargon, citing the\n   hypothesis test or the confidence interval to support your claim.\n   \n  Because p-value < 0.0001 < α = 0.1, we reject H0. There is evidence in favor of the alternative hypothesis, that there is a difference in mean litter size between Feliformia and Caniformia.\n   \n5. Consider again the carnivora dataset, where BW represents birth weight in grams.  Based on the following code, answer the questions below.\n\n\n   ::: {.cell}\n   \n   ```{.r .cell-code}\n   ggplot(carnivora, aes(Family, BW)) + geom_boxplot()\n   ```\n   \n   ::: {.cell-output .cell-output-stderr}\n   \n   ```\n   Warning: Removed 50 rows containing non-finite outside the scale range\n   (`stat_boxplot()`).\n   ```\n   \n   \n   :::\n   \n   ::: {.cell-output-display}\n   ![](exam02practice_solutions_files/figure-html/unnamed-chunk-5-1.png){width=672}\n   :::\n   \n   ```{.r .cell-code}\n   fit <- lm(BW ~ Family, data = carnivora)\n   anova(fit)\n   ```\n   \n   ::: {.cell-output .cell-output-stdout}\n   \n   ```\n   Analysis of Variance Table\n   \n   Response: BW\n             Df  Sum Sq Mean Sq F value    Pr(>F)    \n   Family     7 3256952  465279   6.142 2.648e-05 ***\n   Residuals 54 4090670   75753                      \n   ---\n   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n   ```\n   \n   \n   :::\n   \n   ```{.r .cell-code}\n   TukeyHSD(aov(fit))\n   ```\n   \n   ::: {.cell-output .cell-output-stdout}\n   \n   ```\n     Tukey multiple comparisons of means\n       95% family-wise confidence level\n   \n   Fit: aov(formula = fit)\n   \n   $Family\n                                 diff         lwr        upr     p adj\n   Canidae-Ailuridae        101.68182  -804.63402 1007.99765 0.9999624\n   Felidae-Ailuridae        313.26250  -581.17450 1207.69950 0.9531564\n   Hyaenidae-Ailuridae      991.70000   -71.04952 2054.44952 0.0839689\n   Mustelidae-Ailuridae     -47.33933  -943.52842  848.84975 0.9999998\n   Procyonidae-Ailuridae      6.30000  -963.85314  976.45314 1.0000000\n   Ursidae-Ailuridae        537.40000  -464.56985 1539.36985 0.6928677\n   Viverridae-Ailuridae      -8.20000  -918.28431  901.88431 1.0000000\n   Felidae-Canidae          211.58068  -128.28776  551.44912 0.5157207\n   Hyaenidae-Canidae        890.01818   222.98779 1557.04857 0.0023455\n   Mustelidae-Canidae      -149.02115  -493.47417  195.43186 0.8692106\n   Procyonidae-Canidae      -95.38182  -602.02777  411.26413 0.9988257\n   Ursidae-Canidae          435.71818  -129.46904 1000.90540 0.2480542\n   Viverridae-Canidae      -109.88182  -489.02093  269.25730 0.9834466\n   Hyaenidae-Felidae        678.43750    27.63899 1329.23601 0.0352976\n   Mustelidae-Felidae      -360.60183  -672.46244  -48.74123 0.0130218\n   Procyonidae-Felidae     -306.96250  -792.03907  178.11407 0.4946297\n   Ursidae-Felidae          224.13750  -321.79817  770.07317 0.8970179\n   Viverridae-Felidae      -321.46250  -671.25619   28.33119 0.0932343\n   Mustelidae-Hyaenidae   -1039.03933 -1692.24376 -385.83491 0.0001564\n   Procyonidae-Hyaenidae   -985.40000 -1736.87739 -233.92261 0.0029540\n   Ursidae-Hyaenidae       -454.30000 -1246.42672  337.82672 0.6174485\n   Viverridae-Hyaenidae    -999.90000 -1672.04181 -327.75819 0.0004772\n   Procyonidae-Mustelidae    53.63933  -434.66037  541.93904 0.9999674\n   Ursidae-Mustelidae       584.73933    35.93784 1133.54082 0.0290616\n   Viverridae-Mustelidae     39.13933  -315.11051  393.38917 0.9999661\n   Ursidae-Procyonidae      531.10000  -131.64076 1193.84076 0.2066827\n   Viverridae-Procyonidae   -14.50000  -527.85679  498.85679 1.0000000\n   Viverridae-Ursidae      -545.60000 -1116.81070   25.61070 0.0710874\n   ```\n   \n   \n   :::\n   :::\n\n   \n   a. Is the group degrees of freedom correct? Explain.\n   \n   Yes, for ANOVA, the group degrees of freedom is always the number of groups 8 minus 1 = 7.\n   \n   b. What is the appropriate statistical conclusion from this test?\n   \n   Reject H0\n   \n   c. Write an interpretation of the conclusion with minimal statistical jargon.\n   \n   There is at least one family with a mean birth weight different from the other families.  Some families of the order Carnivora have different mean birth weight.\n   \n   d. Explain why it is appropriate to use Tukey's HSD here.\n   \n   Because we rejected H0\n   \n   e. What does Tukey's HSD tell you about these possums?\n   \n   The families Hyaenidae and Canidae have differing mean birth weight (p-value = 0.002), but the families Mustelidae and Canidae do not (p-value = 0.869).\n\n",
    "supporting": [
      "exam02practice_solutions_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}