{
  "hash": "356221f1e9f827846d3cba325cc3c3df",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Simple Linear Regression\"\naffiliation: \"CSU, Chico MATH 315\"\nauthor: \"Edward A. Roualdes\"\nformat:\n  revealjs:\n    incremental: true\n    scrollable: true\n    code-fold: true\n    self-contained: true\ntbl-cap-location: bottom\nexecute:\n  echo: true\n---\n\n\n\n# Recap\n\n## recap: point estimates\n\nPoint estimates are random variables.  Random variables follow shapes, called\ndistributions.  Therefore, point estimates follow distributions (and have\nshapes) named sampling distributions.\n\n## recap: standard errors\n\nThe standard deviation of a sampling distribution is called a standard error.\nThe standard error shrinks with the square root of the sample size.\n\n\n## recap: central limit theorem\n\nThe Central Limit Theorem says, \"If our sample size is large enough, the sample\nmean will be approximately Normally distributed.\"\n\n\n## recap: confidence intervals\n\nFrom the CLT, we can approximate confidence intervals from an approximate\n*sampling distribution*.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](main_files/figure-revealjs/unnamed-chunk-2-1.png){width=960}\n:::\n:::\n\n\n## recap: hypothesis tests\n\nFrom the CLT, we can approximate area in tails (p-values) from an approximate\n*sampling distribution*.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](main_files/figure-revealjs/unnamed-chunk-3-1.png){width=960}\n:::\n:::\n\n\n## recap: ANOVA\n\nANOVA breaks up means of numerical response variable by levels of one\ncategorical variable.\n\n## recap: scatter plot\n\nScatterplots are  a graphical description of two numerical variables; consider\nDarwin's finch data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nurl <- \"https://raw.githubusercontent.com/roualdes/data/master/finches.csv\"\nfinch <- read.csv(url)\nggplot(data=finch, aes(middletoelength, winglength)) +\n    geom_point() +\n    labs(xlab=\"Middle toe length (mm)\",\n         ylab=\"Wing length (mm)\")\n```\n\n::: {.cell-output-display}\n![](main_files/figure-revealjs/unnamed-chunk-4-1.png){width=960}\n:::\n:::\n\n\n## recap: scatter plot, take 2\n\nSome keywords to describe scatterplots\n\n* associated or not.\n* direction: positive or negative association.\n* structure: linear or nonlinear.\n\n## Correlation, definition\n\n\n**Correlation** is (often/sometimes) denoted by $R$ and is the numeric analogue\nof the words above.\n\n* **Correlation** describes the strength of the linear relationship between two\n  variables, and always takes values between -1 and 1.\n\n\n## Correlation, notes\n\nNotes on correlation\n\n* More accurate name is Pearson correlation coefficient.\n* Describes linear relationships only.\n* Bounded by -1 and 1.\n* The value $0$ denotes no association.\n* The sign dictates directionality.\n\n\n## Correlation, R code\n\nIn R we should just use the function `cor`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(finch$middletoelength, finch$winglength)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7034241\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n## Correlation,  example\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](main_files/figure-revealjs/unnamed-chunk-7-1.png){width=960}\n:::\n:::\n\n\n## Correlation,  example\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](main_files/figure-revealjs/unnamed-chunk-8-1.png){width=960}\n:::\n:::\n\n\n## Correlation, example\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](main_files/figure-revealjs/unnamed-chunk-9-1.png){width=960}\n:::\n:::\n\n\n## Correlation,  example\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](main_files/figure-revealjs/unnamed-chunk-10-1.png){width=960}\n:::\n:::\n\n\n## Correlation,  example\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](main_files/figure-revealjs/unnamed-chunk-11-1.png){width=960}\n:::\n:::\n\n\n## Correlation,  example\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](main_files/figure-revealjs/unnamed-chunk-12-1.png){width=960}\n:::\n:::\n\n\n## Correlation,  example\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](main_files/figure-revealjs/unnamed-chunk-13-1.png){width=960}\n:::\n:::\n\n\n\n## Correlation,  example\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](main_files/figure-revealjs/unnamed-chunk-14-1.png){width=960}\n:::\n:::\n\n\n## Correlation,  example\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](main_files/figure-revealjs/unnamed-chunk-15-1.png){width=960}\n:::\n:::\n\n\n## Correlation, (watch out)  example\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](main_files/figure-revealjs/unnamed-chunk-16-1.png){width=960}\n:::\n:::\n\n\n\n## Correlation, (watch out) example\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](main_files/figure-revealjs/unnamed-chunk-17-1.png){width=960}\n:::\n:::\n\n\n\n## Correlation, plots\n\nThis is another reason plots are so important.\n\n\n# Simple Linear Regression\n\n## Linear Regression, introduction\n\nFor all of the appropriately linear correlation examples above, it was easy to\nthink about a line through the data and then ask, \"How closely do the data fall\nonto that line?\"  That line through the data however, has a name and a\nmathematical definition.\n\n## lite example\n\nThe **least squares line** for Darwin's finch data is plot below in blue.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=finch, aes(middletoelength, winglength)) +\n    geom_point() +\n    labs(xlab=\"Middle toe length (mm)\",\n         ylab=\"Wing length (mm)\") +\n    stat_smooth(method=\"lm\", se=FALSE)\n```\n\n::: {.cell-output-display}\n![](main_files/figure-revealjs/unnamed-chunk-18-1.png){width=960}\n:::\n:::\n\n\n## Linear Regression, idea\n\nSimple linear regression decomposes the response variable $Y$ into three components:\n\n* the **intercept**\n    * the value $Y$ takes on when $X$ is equal to $0$;\n    * above, the length of a wing when the middle toe length is $0$\n\n* the **slope**\n    * on the explanatory variable $X$\n    * represents the increase in $Y$ for a unit increase in $X$;\n    * above, some increase in wing length for every mm increase in the middle toe length\n\n* errors/residuals\n    * some left over bits\n\n## Linear Regression, model\n\n\nGiven a response variable $Y$ and an explanatory variable $X$, the simple linear\nregression model is\n\n\n$$Y = \\underbrace{\\beta_0}_{\\text{intercept}} + \\underbrace{\\beta_1}_{\\text{slope}} X + \\underbrace{\\epsilon}_{\\text{errors}}$$\n\n## Simple Linear Regression, parameters\n\nThe population parameters $\\beta_0$ and $\\beta_1$ are estimated with\n$\\hat{\\beta}_0$ and $\\hat{\\beta}_1$.  These estimates within the linear\nregression equation are written\n\n\n$$\\hat{Y} = \\hat{\\beta}_0 + \\hat{\\beta}_1 X$$\n\nThe predicted/fitted value of $Y$ is a function of the estimates of the intercept and\nslope, dependent on some value of $X$.\n\n\n## Linear Regression, residuals\n\nNot every observation will fall of the least squares line.  The difference\nbetween the true observation $Y_i$ and the predicted value of $\\hat{Y}_i$ at\n$X_i$, is the $i$th residual\n\n\n$$e_i = Y_i - \\hat{Y}_i = Y_i - (\\hat{\\beta}_0 + \\hat{\\beta}_1 X_i)$$\n\n## Simple Linear Regression, residuals by picture\n\nSome residuals will be positive and some negative.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](main_files/figure-revealjs/unnamed-chunk-19-1.png){width=960}\n:::\n:::\n\n\n## Simple Linear Regression, best\n\nThe word \"best\" is cleverly defined and not without debate.  The most common\ndefinition of best means the line that minimizes the sum of the squared\nresiduals.  This idea is intuitive.  We are to find the values of $\\beta_0$ and\n$\\beta_1$ that\n\n* take $e_i = Y_i - \\hat{Y}_i$, for all $i$,\n* square each residual, $e_i^2$, and\n* minimize $\\frac{1}{n} \\sum_{i=1}^n e_i^2$.\n\n\n## Simple Linear Regression in R\n\nIn R we use the function `lm` to fit linear regression.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- lm(winglength ~ middletoelength, data = finch)\n## summary(fit) # RStudio\n## yhat <- fitted(fit) # predicted/fitted values\n## e <- residuals(fit) # resiudal values\n```\n:::\n\n\n## Simple Linear Regression, interpretation\n\nThe coefficients from the model can be extracted with the function `coefficients`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(beta <- coefficients(fit))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    (Intercept) middletoelength \n      23.751547        2.494932 \n```\n\n\n:::\n:::\n\n\nThus, our fitted linear model is written as\n\n$$\\hat{Y} = 23.75 + 2.49 X$$\n\n\n# Example\n\n## Elmhurst Colege Data\n\nWe'll consider a dataset named  `elmhurst`.  With these data, we might have the\nquestion, \"How is family income related to the amount of gift aid a student\nreceives from the college?\"\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nurl <- \"https://raw.githubusercontent.com/roualdes/data/master/elmhurst.csv\"\nelmhurst <- read.csv(url)\nhead(elmhurst)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  family_income gift_aid price_paid\n1        92.922    21.72      14.28\n2         0.250    27.47       8.53\n3        53.092    27.75      14.25\n4        50.200    27.22       8.78\n5       137.613    18.00      24.00\n6        47.957    18.52      23.48\n```\n\n\n:::\n:::\n\n\n## Elmhurst College Data\n\nStep 1?\n\n## Elmhurst College Data\n\nPlot the data!\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(elmhurst$family_income, elmhurst$gift_aid)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.4985561\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(data = elmhurst, aes(family_income, gift_aid),\n       ylab=\"Gift aid ($1000)\",\n       xlab=\"Family income ($1000)\") +\n    geom_point()\n```\n\n::: {.cell-output-display}\n![](main_files/figure-revealjs/unnamed-chunk-23-1.png){width=960}\n:::\n:::\n\n\n## Elmhurst College Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = elmhurst, aes(family_income, gift_aid),\n       ylab=\"Gift aid ($1000)\",\n       xlab=\"Family income ($1000)\") +\n    geom_point() +\n    stat_smooth(method = \"lm\", se = FALSE) # no standard errors\n```\n\n::: {.cell-output-display}\n![](main_files/figure-revealjs/unnamed-chunk-24-1.png){width=960}\n:::\n:::\n\n\n## Elmhurst College Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nelmReg <- lm(gift_aid ~ family_income, data=elmhurst)\n## summary(elmReg) ## RStudio\n## yhat <- fitted(elmReg)\n## e <- residuals(elmReg)\n```\n:::\n\n\n## Elmhurst College Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoef(elmReg)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  (Intercept) family_income \n  24.31932901   -0.04307165 \n```\n\n\n:::\n:::\n\n\n## Elmhurst College Data\n\nOur estimated linear model looks like\n\n$$\\widehat{aid} = 23.75 + 2.49 \\times family\\_income$$\n\nHow do we interpret this?  Can we make causal connections from this model?\n\n\n## Take Away\n\n* Correlation is a helpful summary statistic between two numerical variables\n* Linear regression fits \"best\" line through scatterplot\n* best means minimized squared residuals\n* expected value of response given some value of explanatory\n",
    "supporting": [
      "main_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}