{
  "hash": "0346ec1f4d29c3bcebb2798e7e8c1dab",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Plotting Data\"\naffiliation: \"CSU, Chico MATH 315\"\nauthor: \"Edward A. Roualdes\"\nformat:\n  revealjs:\n    incremental: true\n    scrollable: true\n    code-fold: show\n    self-contained: true\ntbl-cap-location: bottom\nexecute:\n  echo: true\n---\n\n# Categorical Data\n\n\n## Visualizing Categorical Variables\n\nWith categorial data we can make **bar charts**.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsuppressMessages(library(tidyverse))\nsuppressMessages(library(openintro))\ndata(email)\nggplot(data = email, aes(number)) +\n    geom_bar() +\n    labs(title = \"email 'Number' Frequency\")\n```\n\n::: {.cell-output-display}\n![](main_files/figure-revealjs/unnamed-chunk-1-1.png){width=960}\n:::\n:::\n\n\n## `county`\n\nRecall the county data set? How big?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(county)\ntail(county[, c(\"state\", \"name\")])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n  state   name             \n  <fct>   <chr>            \n1 Wyoming Sublette County  \n2 Wyoming Sweetwater County\n3 Wyoming Teton County     \n4 Wyoming Uinta County     \n5 Wyoming Washakie County  \n6 Wyoming Weston County    \n```\n\n\n:::\n:::\n\n\n\n## `county`\n\nFrequency table of county data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(county$state)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n             Alabama               Alaska              Arizona \n                  67                   29                   15 \n            Arkansas           California             Colorado \n                  75                   58                   64 \n         Connecticut             Delaware District of Columbia \n                   8                    3                    1 \n             Florida              Georgia               Hawaii \n                  67                  159                    5 \n               Idaho             Illinois              Indiana \n                  44                  102                   92 \n                Iowa               Kansas             Kentucky \n                  99                  105                  120 \n           Louisiana                Maine             Maryland \n                  64                   16                   24 \n       Massachusetts             Michigan            Minnesota \n                  14                   83                   87 \n         Mississippi             Missouri              Montana \n                  82                  115                   56 \n            Nebraska               Nevada        New Hampshire \n                  93                   17                   10 \n          New Jersey           New Mexico             New York \n                  21                   33                   62 \n      North Carolina         North Dakota                 Ohio \n                 100                   53                   88 \n            Oklahoma               Oregon         Pennsylvania \n                  77                   36                   67 \n        Rhode Island       South Carolina         South Dakota \n                   5                   46                   66 \n           Tennessee                Texas                 Utah \n                  95                  254                   29 \n             Vermont             Virginia           Washington \n                  14                  133                   39 \n       West Virginia            Wisconsin              Wyoming \n                  55                   72                   23 \n```\n\n\n:::\n:::\n\n\n## `county`\n\nBar chart of county data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(pl <- ggplot(data = county, aes(state)) +\n     geom_bar() +\n     labs(title = \"?\", x = \"States\"))\n```\n\n::: {.cell-output-display}\n![](main_files/figure-revealjs/unnamed-chunk-4-1.png){width=960}\n:::\n:::\n\n\n\n## `county`\n\n\n::: {.cell}\n\n```{.r .cell-code}\npl + theme(axis.text.x = element_text(angle = 45,\n    hjust=1))\n```\n\n::: {.cell-output-display}\n![](main_files/figure-revealjs/unnamed-chunk-5-1.png){width=960}\n:::\n:::\n\n\n\n# Numerical Data\n\n## Towards Histograms\n\nWhat do we give up by finding a mean? Consider `county`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(county$per_capita_income, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 26093.12\n```\n\n\n:::\n\n```{.r .cell-code}\nmin(county$per_capita_income, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10466.84\n```\n\n\n:::\n\n```{.r .cell-code}\nmax(county$per_capita_income, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 69532.86\n```\n\n\n:::\n:::\n\n\n\n## Histograms\n\nA histogram helps summarize tails of the data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(p <- ggplot(data = county, aes(per_capita_income)) +\n     geom_histogram(bins = 21) +\n     labs(x = \"Per capita income\"))\n```\n\n::: {.cell-output-display}\n![](main_files/figure-revealjs/unnamed-chunk-7-1.png){width=960}\n:::\n:::\n\n\n\n## Histograms, in words\n\n\nThink of each observation as belonging to a **bin**.  These binned observations\nare plotted as bars to form a histogram.  That is, the height of each bar\ndepicts the number of observations within each bin.\n\n* The `county$per_capita_income` data has data from $10,466.84 up to\n  $69,532.86.  Setting `binwidth = 1800` creates bins of width 1,800\n  and places the appropriate observations in each.  Observations on\n  the boundary of a bin are allocated to the lower bin.\n\n\n## Histograms, picking bins\n\nSince the researcher has to choose the bin width, we should learn the\ndifference between bins that are too small and bins that are too wide.\n\n\n## Histograms, too many\n\nExtremely small bins\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = county, aes(per_capita_income)) +\n    geom_histogram(binwidth = 3) +\n    labs(x = \"Per capita income\")\n```\n\n::: {.cell-output-display}\n![](main_files/figure-revealjs/unnamed-chunk-8-1.png){width=960}\n:::\n:::\n\n\n\n## Histograms, too few\n\nExtremely large bins\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = county, aes(per_capita_income)) +\n    geom_histogram(binwidth = 80000) +\n    labs(x = \"Per capita income\")\n```\n\n::: {.cell-output-display}\n![](main_files/figure-revealjs/unnamed-chunk-9-1.png){width=960}\n:::\n:::\n\n\n\n## Histograms, by group\n\nCompare chicken weights by diet.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=ChickWeight, aes(weight)) +\n    geom_histogram(bins = 21) +\n    facet_wrap(Diet ~ ., ncol = 1)\n```\n\n::: {.cell-output-display}\n![](main_files/figure-revealjs/unnamed-chunk-10-1.png){width=960}\n:::\n:::\n\n\n\n## Histograms, keywords\n\n* **right skewed**. When data trail to the right and have a longer right tail,\n  the shape is said to be right skewed.\n\n* **left skewed**. Data with the reverse characteristic -- a long, thin\n  tail to the left -- are said to be left skewed.\n\n* **symmetric**. Data that show roughly equal tails in both directions are\n  called symmetric.\n\n\n## Histograms, and measures of center\n\nWhere is the mean on a histogram?  Median?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmn <- mean(county$per_capita_income, na.rm = TRUE)\nmdn <- median(county$per_capita_income, na.rm = TRUE)\np + geom_vline(aes(xintercept=mn), color=\"red\", size=1) +\n    geom_vline(aes(xintercept=mdn), color=\"blue\", size=1)\n```\n\n::: {.cell-output-display}\n![](main_files/figure-revealjs/unnamed-chunk-11-1.png){width=960}\n:::\n:::\n\n\n\n## Histograms, they tell us more\n\nWhat more, other than the center of the data, do histograms tell us? Consider a\nhistogram from the `email` data set.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nem <- mean(email$num_char)\nggplot(data=email, aes(num_char)) +\n    geom_histogram(bins = 21) +\n    geom_vline(aes(xintercept = em), color = \"blue\")\n```\n\n::: {.cell-output-display}\n![](main_files/figure-revealjs/unnamed-chunk-12-1.png){width=960}\n:::\n:::\n\n\n\n## Histograms, an ideal\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](main_files/figure-revealjs/unnamed-chunk-13-1.png){width=960}\n:::\n:::\n\n\n## Data Width, 1 standard deviation\n\nHistograms naturally connect with **standard deviations**.  If the data are\n**unimodal** (ish) and symmetric (ish), roughly 68% of the data will be within\none standard deviation of the mean.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](main_files/figure-revealjs/unnamed-chunk-14-1.png){width=960}\n:::\n:::\n\n\n\n## Data Width, 2 standard deviations\n\nIf the data are **unimodal** (ish) and symmetric (ish), roughly 95% of the data\nwill be within two standard deviations of the mean.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](main_files/figure-revealjs/unnamed-chunk-15-1.png){width=960}\n:::\n:::\n\n\n## Data Width, 3 standard deviations\n\nIf the data are **unimodal** (ish) and symmetric (ish), roughly 99.7% of the data\nwill be within three standard deviations of the mean.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](main_files/figure-revealjs/unnamed-chunk-16-1.png){width=960}\n:::\n:::\n\n\n\n## Standard Deviations, be careful\n\nThree different population distributions with the same (population) mean\n$\\mu$ = 0 and (population) standard deviation $\\sigma = 1$.\n\n\n![](figs/distsM0SD1.png){fig-align=\"center\"}\n\n\n## Towards Box plots\n\nWe will use the data set `carnivora` found within the library `ape`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ape)\ndata(carnivora)\n# ?carnivora\n```\n:::\n\n\n\n## recap: summary statistics\n\nR will fairly easily produce six number summaries for us.  Here's the\nvariable for average brain weight amongst male and female animals from\nthe order Carnivora.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(carnivora$SB)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   1.00   15.68   33.75   56.43   57.17  459.50 \n```\n\n\n:::\n:::\n\n\n\n## Box Plots\n\nA **box plot** summarizes a data set using five (standard) statistics\nwhile also plotting unusual observations.\n\n\n## Box Plot, explained\n\n![](figs/boxplot_explained.png){fig-align=\"center\"}\n\n\n## Box Plot, carnivora example\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = carnivora, aes(Order, SB)) +\n    geom_boxplot() +\n    labs(y = \"Average brain weight (g)\",\n         x = \"Order\")\n```\n\n::: {.cell-output-display}\n![](main_files/figure-revealjs/unnamed-chunk-19-1.png){width=960}\n:::\n:::\n\n\n## Box Plot, better carnivora example\n\nHave you seen some of the families in carnivora? From adorable,\n[Ailuridae](https://en.wikipedia.org/wiki/Ailuridae), to huge,\n[Ursidae](https://en.wikipedia.org/wiki/Bear).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = carnivora, aes(Family, SB)) +\n    geom_boxplot() +\n    labs(x = \"Family\", y = \"Average brain weight (g)\")\n```\n\n::: {.cell-output-display}\n![](main_files/figure-revealjs/unnamed-chunk-20-1.png){width=960}\n:::\n:::\n\n\n\n## Towards scatter plots\n\nThe most common bivariate plot is the **scatter plot**.\n\nA scatterplot provides a case-by-case view of data for two numerical\nvariables.\n\n\n## Scatterplot, `carnivora` example\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = carnivora, aes(SW, SB)) +\n    geom_point() +\n    labs(x = \"Average body weight (kg)\",\n         y = \"Average brain weight (g)\")\n```\n\n::: {.cell-output-display}\n![](main_files/figure-revealjs/unnamed-chunk-21-1.png){width=960}\n:::\n:::\n\n\n## Scatter plots, keywords\n\n* **associated**. When two variables show some connection with one\n  another, they are called associated variables.\n\n\n* **independent**. If two variables are not associated, then they are\n  said to be independent.\n\n\n## Scatter plots, keywords\n\nDirection of association can be described as\n\n* **positive association**. When two variables have an upward/positive\n  trend, they are called positively associated.\n\n* **negative association**. When two variables have a\n  downward/negative trend, they are called negatively associated.\n\n## Scatter plots, keywords\n\nStructure of association can be described as **linear** or\n**non-linear**.\n\n\n## Scatter plot, `Indometh` example\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(datasets)\n# ?Indometh\nggplot(data = Indometh, aes(time, conc)) +\n    geom_point()\n```\n\n::: {.cell-output-display}\n![](main_files/figure-revealjs/unnamed-chunk-22-1.png){width=960}\n:::\n:::\n\n\n\n\n## Scatter plot, `CO2` example\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ?CO2\nggplot(data = CO2, aes(conc, uptake, colour = Type)) +\n    geom_point()\n```\n\n::: {.cell-output-display}\n![](main_files/figure-revealjs/unnamed-chunk-23-1.png){width=960}\n:::\n:::\n\n\n\n## Scatter plots, careful\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# x: Australian residents, quarterly 03/1971 - 03/1994\n# y: WI beaver body temps, 10 min intervals\ndf <- data.frame(x = as.vector(austres),\n                 y = beaver1[1:length(austres), \"temp\"])\nggplot(data = df, aes(x, y)) +\n    geom_point()\n```\n\n::: {.cell-output-display}\n![](main_files/figure-revealjs/unnamed-chunk-24-1.png){width=960}\n:::\n:::\n\n\n\n## for fun\n\n![](figs/correlation.png)\n\n<https://xkcd.com/552/>\n\n\n## Take Away\n\n* categorical variable -> bar chart\n* one numerical variable -> histogram\n* one numerical and one categorical -> box plot\n* two numerical -> scatter plot\n* ... many variations\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}