{
  "hash": "378a35f1edc58d8ca05942fa7c53f0af",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"MATH 456 Practice Exam 01 Solutions, Spring 26\"\nformat: html\neditor: source\n---\n\n\n::: {.cell}\n\n:::\n\n\nConsider a data set about finches (little birds) from the Galapagos islands. We'll consider the variables `beakwidth` measured in millimeters (mm), `taillength` also in mm, and `island`.\n\n<!--# EAR  -->\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](exam01_practice_solutions_files/figure-html/unnamed-chunk-2-1.png){fig-align='center' width=288}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Df   Sum Sq Mean Sq F value Pr(>F)\nisland     -  14.6734  7.3367  1.0632 0.3513\nResiduals 65 448.5518  6.9008       -      -\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = taillength ~ island, data = df)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-9.4667 -1.4769  0.3333  1.5026  4.4923 \n\nCoefficients:\n                   Estimate Std. Error t value Pr(>|t|)    \n(Intercept)         44.0077     0.5152  85.421   <2e-16 ***\nislandsancristobal   0.4590     0.7218   0.636    0.527    \nislandsantacruz     -0.7744     0.8517  -0.909    0.367    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.627 on 65 degrees of freedom\nMultiple R-squared:  0.03168,\tAdjusted R-squared:  0.001882 \nF-statistic: 1.063 on 2 and 65 DF,  p-value: 0.3513\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = fita)\n\n$island\n                             diff       lwr       upr     p adj\nsancristobal-floreana   0.4589744 -1.272307 2.1902559 0.8009421\nsantacruz-floreana     -0.7743590 -2.817310 1.2685920 0.6365176\nsantacruz-sancristobal -1.2333333 -3.262396 0.7957293 0.3178053\n```\n\n\n:::\n:::\n\n\n1.  Write three sentences about three different statistics from the box plot above. Each sentence must be about a different island.\n\n    The median tail length for finches from Floreana is about 44mm. The minimum tail length for finches from San Cristobal is about 35mm. The third quartile of tail length for finches from the island Santa Cruz is about 44mm.\n\n2.  Write the null and alternative hypotheses for ANOVA based on the box plot above. Specify a level of significance.\n\n    $H_0: \\mu_f = \\mu_l = \\mu_z$\n\n    $H_1:$ at least one mean is different\n\n    $\\alpha = 0.05$\n\n3.  Compare the p-value to the level of significance and make a conclusion.\n\nThe p-value $= 0.3513 > \\alpha = 0.05$. Therefore fail to reject $H_0$.\n\n4.  Interpret your conclusion in context of the data.\n\nThe mean tail lengths of finches from three islands are nearly equivalent.\n\n5.  What should the degrees of freedom for `island` be for the ANOVA above?\n\nnumber of groups - 1 \\$ = 2\\$\n\n6.  Reproduce the F statistic (named F.value in the output above).\n\n$7.3367 / 6.9008$\n\n7.  Write down the fitted regression equation for the model above.\n\n$\\widehat{taillength} = 44.01 + 0.461_l - 0.77 1_z$\n\n8.  Using Tukey's HSD, write down appropriate null and alternative hypotheses for one comparison. Make a conclusion by quoting an appropriate p-value and then interpret your conclusion in context of the data.\n\nSilly, Edward, Tukey's HSD isn't appropriate here since we failed to reject the null hypothesis from ANOVA.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(fita, newdata = data.frame(island = \"floreana\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       1 \n44.00769 \n```\n\n\n:::\n:::\n\n\n9.  Still using the ANOVA model from above, named `fita`, interpret the prediction in context of the data.\n\n    We expect a finch from Floreana to have a tail length of around 44.01mm.\n\n10. Explain why all finches from the island Floreana have the same prediction for this model.\n\n    ANOVA as a predictive model, predicts each group (island, in this case) by the group mean. The mean for finches from Floreana is 44.01mm.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](exam01_practice_solutions_files/figure-html/unnamed-chunk-4-1.png){fig-align='center' width=288}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = taillength ~ beakwidth, data = df)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4.0270 -0.7880 -0.0112  1.3757  3.8055 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  31.5885     1.4682  21.515  < 2e-16 ***\nbeakwidth     1.2217     0.1426   8.564 2.59e-12 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.823 on 66 degrees of freedom\nMultiple R-squared:  0.5264,\tAdjusted R-squared:  0.5192 \nF-statistic: 73.35 on 1 and 66 DF,  p-value: 2.594e-12\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   5 %      95 %\n(Intercept) 29.1392236 34.037862\nbeakwidth    0.9837041  1.459652\n```\n\n\n:::\n:::\n\n\n11. Write the null and alternative hypotheses for the hypothesis test of the intercept. Specify a level of significance.\n\n$H_0: \\beta_0 = 0$\n\n$H_1: \\beta_0 \\ne 0$\n\n$\\alpha = 0.05$\n\n12. Make the appropriate conclusion from the hypothesis test above. Quote the appropriate p-value.\n\np-value $< 0.0001 < \\alpha = 0.05$, therefore reject $H_0$.\n\n13. Interpret your conclusion in context of the data.\n\nWhen `beakwidth` is equal to 0mm, we expect the tail length of the finches to be statistically significantly different from zero, and specifically to be about 31.59mm.\n\n14. Write down the fitted regression equation for the model above.\n\n$\\widehat{taillength} = 31.59 + 1.22 * beakwidth$\n\n15. Interpret adjusted $R^2$ in context of the data.\n\n$51.92$% of the variation in `taillength` is explained by this linear regression model on `beakwdith`.\n\n16. Provide two reasons $R^2$ is worse than adjusted $R^2$?\n\n<!-- -->\n\ni.  $R^2$ goes up (inappropriately) even when poor predictors are added to the model.\nii. $R^2$ provides a more clearly biased estimate of the percent of the variation that is accounted for by the linear model.\n\n<!-- -->\n\n17. Interpret in context of the data a 90% confidence interval for the intercept.\n\n    We are 90% confident that when beakwidth is equal to 0mm, the tail length of finches from any of these three islands is between 29.14 and 34.04mm.\n\n18. Does the intercept make sense in context of the data. Why or why not?\n\n    Not really, as there are not likely to be any living finches with a beak width of 0mm.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(fitl, newdata=data.frame(beakwidth=5), interval=\"confidence\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       fit      lwr      upr\n1 37.69693 36.15838 39.23548\n```\n\n\n:::\n:::\n\n\n19. Interpret in context of the data a 95% confidence interval for a prediction of the mean `taillength` based on the output above.\n\n    We are 95% confident that when a finch from any of these three islands has a beak width of 5mm, we expect that tail length to be between 36.16 and 39.24mm.\n\n20. Without doing any calculations, write the regression equation for the prediction above.\n\n    $31.59 + 1.22 * 5$\n\n21. Name two ways to make more narrow the width of a confidence interval for a mean `taillength`?\n\n    i.  increase the sample size (the number of data),\n    ii. decrease the confidence level,\n    iii. for linear regression, make a confidence interval from a prediction (of a mean) closer to the mean of the x-axis (beakwidth, in this case) variable.\n\n22. Here is pseudo-code for a function that would be passed to `optim`, `R`'s built in optimization function, in order to calculate linear regression coefficients. Explain what each line of code is doing.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nll_lm <- function(theta, data) { # declare function of two variables, optim will minimize over the first\n    x <- data$x # extract x-axis variable from data\n    y <- data$y # extract y-axis variable from data\n    yhat <- theta[1] + theta[2] * x # make prediction from line on x\n    r <- y - yhat # calculate residuals\n    return(sum( r ^ 2 )) # sum of squared residuals, scalar to be minimized\n}\n```\n:::\n\n",
    "supporting": [
      "exam01_practice_solutions_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}