{
  "hash": "c37979834b5cce77744fa512a21b1f86",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Regression Inference\"\nformat: html\neditor: visual\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nsuppressMessages(library(dplyr))\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nelmhurst <- read.csv(\"https://raw.githubusercontent.com/roualdes/data/refs/heads/master/elmhurst.csv\")\n```\n:::\n\n\nWant to predict `gift_aid`, measured in \\$1,000, using `family_income` also measured in \\$1,000.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(elmhurst, aes(family_income, gift_aid)) +\n  geom_point() +\n  geom_smooth(method = \"lm\", se = FALSE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](main_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nThere appears to be a moderate, negative, and linear relationship between family income and gift aid.\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(elmhurst$family_income, elmhurst$gift_aid)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.4985561\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- lm(gift_aid ~ family_income, data = elmhurst)\nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = gift_aid ~ family_income, data = elmhurst)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-10.1128  -3.6234  -0.2161   3.1587  11.5707 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   24.31933    1.29145  18.831  < 2e-16 ***\nfamily_income -0.04307    0.01081  -3.985 0.000229 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.783 on 48 degrees of freedom\nMultiple R-squared:  0.2486,\tAdjusted R-squared:  0.2329 \nF-statistic: 15.88 on 1 and 48 DF,  p-value: 0.0002289\n```\n\n\n:::\n:::\n\n\nFitted regression equation\n\nexpected gift aid = 24.32 + -0.04 * family income\n\nor \n\n$$\\widehat{gift\\_aid} = 24.32 + -0.04 * family\\_income$$\nUse ~~multiple~~ Adjusted R^2: 23.29% of the variation in gift aid is explained by this linear regression model of family income.\n\nIntercept: For a family with \\$0 in income, we expect their gift aid to be \\$2.432\\times 10^{4}. \n\nSlope: For every \\$1,000 increase in family income, we expect gift aid to go down by \\$40.\n\nPrediction: For a family with income of \\$200,000, we expect the student to receive \\$1.5705\\times 10^{4} in gift aid.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(fit, newdata = data.frame(family_income = 200),         \n        interval = \"confidence\", \n        level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     fit     lwr     upr\n1 15.705 13.1739 18.2361\n```\n\n\n:::\n:::\n\n\nPrediction confidence interval: We are 95% confident that for a family with income of \\$200,000, we expect the student to receive gift aid between \\$1.317\\times 10^{4} and \\$1.824\\times 10^{4}.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(fit, level = 0.98)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                      1 %        99 %\n(Intercept)   21.21134898 27.42730904\nfamily_income -0.06908553 -0.01705778\n```\n\n\n:::\n:::\n\n\nConfidence interval for the intercept: We are 98% confident that for a family with \\$0 in income, we expect the student to receive between \\$2.121\\times 10^{4} and \\$2.743\\times 10^{4}.\n\nConfidence interval for the slope: We are 98% confident that for each next \\$1,000 a family earns in income, we expect that amount of gift aid the student receives to go down by between \\$20 and \\$70.\n\n",
    "supporting": [
      "main_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}